image: node:lts

definitions:
  caches:
    pnpm: $BITBUCKET_CLONE_DIR/.pnpm-store

  steps:
    - step: &checks
        name: Lint, Types, Tests
        caches:
          - pnpm
        script:
          - corepack enable
          - corepack prepare pnpm@latest --activate
          - pnpm install
          - pnpm lint
          - pnpm test:types
          - pnpm test

pipelines:
  default:
    - step: *checks

  branches:
    main:
      - step: *checks

  pull-requests:
    main:
      - step: *checks
