minimumReleaseAge: 0

packages:
  - frameworks/*
  - serverless/*
  - templating/*

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  netlify-cli: false
  sharp: false
  unix-dgram: false
  workerd: false
